### ISSUE TITLE
Crash when running for a single platform

### ISSUE THREAD

**Issue by WhyNotHugo** [coreos/cargo-vendor-filterer#60]
```
> cargo vendor-filterer
Gathering metadata for platforms
   Vendoring adler v1.0.2 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/adler-1.0.2) to vendor/adler
   Vendoring android_system_properties v0.1.5 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/android_system_properties-0.1.5) to vendor/android_system_properties
   Vendoring anyhow v1.0.68 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.68) to vendor/anyhow
   Vendoring atty v0.2.14 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/atty-0.2.14) to vendor/atty
   Vendoring autocfg v1.1.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/autocfg-1.1.0) to vendor/autocfg
   Vendoring bitflags v1.3.2 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.3.2) to vendor/bitflags
   Vendoring bumpalo v3.11.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/bumpalo-3.11.1) to vendor/bumpalo
   Vendoring calloop v0.10.5 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/calloop-0.10.5) to vendor/calloop
   Vendoring cc v1.0.78 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.78) to vendor/cc
   Vendoring cfg-if v1.0.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-1.0.0) to vendor/cfg-if
   Vendoring chrono v0.4.23 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.23) to vendor/chrono
   Vendoring clap v4.1.4 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.1.4) to vendor/clap
   Vendoring clap_complete v4.1.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/clap_complete-4.1.1) to vendor/clap_complete
   Vendoring clap_derive v4.1.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/clap_derive-4.1.0) to vendor/clap_derive
   Vendoring clap_lex v0.3.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/clap_lex-0.3.0) to vendor/clap_lex
   Vendoring codespan-reporting v0.11.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/codespan-reporting-0.11.1) to vendor/codespan-reporting
   Vendoring colored v2.0.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/colored-2.0.0) to vendor/colored
   Vendoring core-foundation-sys v0.8.3 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/core-foundation-sys-0.8.3) to vendor/core-foundation-sys
   Vendoring crc32fast v1.3.2 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/crc32fast-1.3.2) to vendor/crc32fast
   Vendoring cxx v1.0.86 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/cxx-1.0.86) to vendor/cxx
   Vendoring cxx-build v1.0.86 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/cxx-build-1.0.86) to vendor/cxx-build
   Vendoring cxxbridge-flags v1.0.86 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/cxxbridge-flags-1.0.86) to vendor/cxxbridge-flags
   Vendoring cxxbridge-macro v1.0.86 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/cxxbridge-macro-1.0.86) to vendor/cxxbridge-macro
   Vendoring dlib v0.5.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/dlib-0.5.0) to vendor/dlib
   Vendoring downcast-rs v1.2.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/downcast-rs-1.2.0) to vendor/downcast-rs
   Vendoring either v1.8.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/either-1.8.0) to vendor/either
   Vendoring errno v0.2.8 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/errno-0.2.8) to vendor/errno
   Vendoring errno-dragonfly v0.1.2 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/errno-dragonfly-0.1.2) to vendor/errno-dragonfly
   Vendoring flate2 v1.0.25 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.25) to vendor/flate2
   Vendoring futures v0.3.25 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.3.25) to vendor/futures
   Vendoring futures-channel v0.3.25 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-0.3.25) to vendor/futures-channel
   Vendoring futures-core v0.3.25 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.25) to vendor/futures-core
   Vendoring futures-io v0.3.25 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/futures-io-0.3.25) to vendor/futures-io
   Vendoring futures-sink v0.3.25 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/futures-sink-0.3.25) to vendor/futures-sink
   Vendoring futures-task v0.3.25 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.25) to vendor/futures-task
   Vendoring futures-util v0.3.25 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.25) to vendor/futures-util
   Vendoring heck v0.4.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/heck-0.4.0) to vendor/heck
   Vendoring hermit-abi v0.1.19 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/hermit-abi-0.1.19) to vendor/hermit-abi-0.1.19
   Vendoring hermit-abi v0.2.6 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/hermit-abi-0.2.6) to vendor/hermit-abi
   Vendoring iana-time-zone v0.1.53 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/iana-time-zone-0.1.53) to vendor/iana-time-zone
   Vendoring iana-time-zone-haiku v0.1.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/iana-time-zone-haiku-0.1.1) to vendor/iana-time-zone-haiku
   Vendoring io-lifetimes v1.0.4 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/io-lifetimes-1.0.4) to vendor/io-lifetimes
   Vendoring is-terminal v0.4.2 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/is-terminal-0.4.2) to vendor/is-terminal
   Vendoring itertools v0.10.5 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/itertools-0.10.5) to vendor/itertools
   Vendoring itoa v1.0.5 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/itoa-1.0.5) to vendor/itoa
   Vendoring js-sys v0.3.60 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/js-sys-0.3.60) to vendor/js-sys
   Vendoring lazy_static v1.4.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0) to vendor/lazy_static
   Vendoring libc v0.2.139 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.139) to vendor/libc
   Vendoring libloading v0.7.4 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/libloading-0.7.4) to vendor/libloading
   Vendoring link-cplusplus v1.0.8 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/link-cplusplus-1.0.8) to vendor/link-cplusplus
   Vendoring linux-raw-sys v0.1.4 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/linux-raw-sys-0.1.4) to vendor/linux-raw-sys
   Vendoring log v0.4.17 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.17) to vendor/log
   Vendoring memchr v2.5.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/memchr-2.5.0) to vendor/memchr
   Vendoring memmap2 v0.5.8 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/memmap2-0.5.8) to vendor/memmap2
   Vendoring memoffset v0.6.5 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/memoffset-0.6.5) to vendor/memoffset-0.6.5
   Vendoring memoffset v0.7.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/memoffset-0.7.1) to vendor/memoffset
   Vendoring minimal-lexical v0.2.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/minimal-lexical-0.2.1) to vendor/minimal-lexical
   Vendoring miniz_oxide v0.6.2 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/miniz_oxide-0.6.2) to vendor/miniz_oxide
   Vendoring nix v0.25.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.25.1) to vendor/nix-0.25.1
   Vendoring nix v0.26.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.26.1) to vendor/nix
   Vendoring nom v7.1.2 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/nom-7.1.2) to vendor/nom
   Vendoring num-integer v0.1.45 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/num-integer-0.1.45) to vendor/num-integer
   Vendoring num-traits v0.2.15 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/num-traits-0.2.15) to vendor/num-traits
   Vendoring once_cell v1.17.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/once_cell-1.17.0) to vendor/once_cell
   Vendoring os_str_bytes v6.4.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/os_str_bytes-6.4.1) to vendor/os_str_bytes
   Vendoring pin-project-lite v0.2.9 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/pin-project-lite-0.2.9) to vendor/pin-project-lite
   Vendoring pin-utils v0.1.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/pin-utils-0.1.0) to vendor/pin-utils
   Vendoring pkg-config v0.3.26 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/pkg-config-0.3.26) to vendor/pkg-config
   Vendoring png v0.17.7 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/png-0.17.7) to vendor/png
   Vendoring proc-macro-error v1.0.4 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4) to vendor/proc-macro-error
   Vendoring proc-macro-error-attr v1.0.4 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-attr-1.0.4) to vendor/proc-macro-error-attr
   Vendoring proc-macro2 v1.0.49 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.49) to vendor/proc-macro2
   Vendoring quick-xml v0.23.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/quick-xml-0.23.1) to vendor/quick-xml
   Vendoring quote v1.0.23 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/quote-1.0.23) to vendor/quote
   Vendoring rustix v0.36.6 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.36.6) to vendor/rustix
   Vendoring ryu v1.0.12 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/ryu-1.0.12) to vendor/ryu
   Vendoring scoped-tls v1.0.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.1) to vendor/scoped-tls
   Vendoring scratch v1.0.3 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/scratch-1.0.3) to vendor/scratch
   Vendoring serde v1.0.152 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.152) to vendor/serde
   Vendoring serde_derive v1.0.152 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/serde_derive-1.0.152) to vendor/serde_derive
   Vendoring serde_json v1.0.91 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.91) to vendor/serde_json
   Vendoring simple_logger v2.3.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/simple_logger-2.3.0) to vendor/simple_logger
   Vendoring slab v0.4.7 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/slab-0.4.7) to vendor/slab
   Vendoring slotmap v1.0.6 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/slotmap-1.0.6) to vendor/slotmap
   Vendoring smallvec v1.10.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/smallvec-1.10.0) to vendor/smallvec
   Vendoring smithay-client-toolkit v0.16.0 (https://github.com/Smithay/client-toolkit.git#327f9cd7) (/home/hugo/.local/state/cargo/git/checkouts/client-toolkit-e56a3844de110279/327f9cd) to vendor/smithay-client-toolkit
   Vendoring static_assertions v1.1.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/static_assertions-1.1.0) to vendor/static_assertions
   Vendoring strsim v0.10.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/strsim-0.10.0) to vendor/strsim
   Vendoring syn v1.0.107 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/syn-1.0.107) to vendor/syn
   Vendoring termcolor v1.1.3 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/termcolor-1.1.3) to vendor/termcolor
   Vendoring thiserror v1.0.38 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/thiserror-1.0.38) to vendor/thiserror
   Vendoring thiserror-impl v1.0.38 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/thiserror-impl-1.0.38) to vendor/thiserror-impl
   Vendoring unicode-ident v1.0.6 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/unicode-ident-1.0.6) to vendor/unicode-ident
   Vendoring unicode-width v0.1.10 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/unicode-width-0.1.10) to vendor/unicode-width
   Vendoring vec_map v0.8.2 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/vec_map-0.8.2) to vendor/vec_map
   Vendoring version_check v0.9.4 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/version_check-0.9.4) to vendor/version_check
   Vendoring wasm-bindgen v0.2.83 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-0.2.83) to vendor/wasm-bindgen
   Vendoring wasm-bindgen-backend v0.2.83 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-backend-0.2.83) to vendor/wasm-bindgen-backend
   Vendoring wasm-bindgen-macro v0.2.83 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-macro-0.2.83) to vendor/wasm-bindgen-macro
   Vendoring wasm-bindgen-macro-support v0.2.83 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-macro-support-0.2.83) to vendor/wasm-bindgen-macro-support
   Vendoring wasm-bindgen-shared v0.2.83 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-shared-0.2.83) to vendor/wasm-bindgen-shared
   Vendoring wayland-backend v0.1.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-backend-0.1.0) to vendor/wayland-backend
   Vendoring wayland-client v0.30.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-client-0.30.0) to vendor/wayland-client
   Vendoring wayland-cursor v0.30.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-cursor-0.30.0) to vendor/wayland-cursor
   Vendoring wayland-protocols v0.30.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-protocols-0.30.0) to vendor/wayland-protocols
   Vendoring wayland-protocols-wlr v0.1.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-protocols-wlr-0.1.0) to vendor/wayland-protocols-wlr
   Vendoring wayland-scanner v0.30.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-scanner-0.30.0) to vendor/wayland-scanner
   Vendoring wayland-sys v0.30.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/wayland-sys-0.30.1) to vendor/wayland-sys
   Vendoring winapi v0.3.9 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/winapi-0.3.9) to vendor/winapi
   Vendoring winapi-i686-pc-windows-gnu v0.4.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/winapi-i686-pc-windows-gnu-0.4.0) to vendor/winapi-i686-pc-windows-gnu
   Vendoring winapi-util v0.1.5 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/winapi-util-0.1.5) to vendor/winapi-util
   Vendoring winapi-x86_64-pc-windows-gnu v0.4.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/winapi-x86_64-pc-windows-gnu-0.4.0) to vendor/winapi-x86_64-pc-windows-gnu
   Vendoring windows-sys v0.42.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/windows-sys-0.42.0) to vendor/windows-sys
   Vendoring windows_aarch64_gnullvm v0.42.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/windows_aarch64_gnullvm-0.42.1) to vendor/windows_aarch64_gnullvm
   Vendoring windows_aarch64_msvc v0.42.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/windows_aarch64_msvc-0.42.1) to vendor/windows_aarch64_msvc
   Vendoring windows_i686_gnu v0.42.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/windows_i686_gnu-0.42.1) to vendor/windows_i686_gnu
   Vendoring windows_i686_msvc v0.42.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/windows_i686_msvc-0.42.1) to vendor/windows_i686_msvc
   Vendoring windows_x86_64_gnu v0.42.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/windows_x86_64_gnu-0.42.1) to vendor/windows_x86_64_gnu
   Vendoring windows_x86_64_gnullvm v0.42.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/windows_x86_64_gnullvm-0.42.1) to vendor/windows_x86_64_gnullvm
   Vendoring windows_x86_64_msvc v0.42.1 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/windows_x86_64_msvc-0.42.1) to vendor/windows_x86_64_msvc
   Vendoring xcursor v0.3.4 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/xcursor-0.3.4) to vendor/xcursor
   Vendoring xkbcommon v0.5.0 (/home/hugo/.local/state/cargo/registry/src/github.com-1ecc6299db9ec823/xkbcommon-0.5.0) to vendor/xkbcommon
To use vendored sources, add this to your .cargo/config.toml for this project:

[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/Smithay/client-toolkit.git"]
git = "https://github.com/Smithay/client-toolkit.git"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
Skipping shotman
Skipping shotman_completions
Skipping smithay-client-toolkit
Replacing unreferenced package with stub: android_system_properties
Replacing unreferenced package with stub: bumpalo
Replacing unreferenced package with stub: codespan-reporting
Replacing unreferenced package with stub: core-foundation-sys
Replacing unreferenced package with stub: cxx
Replacing unreferenced package with stub: cxx-build
Replacing unreferenced package with stub: cxxbridge-flags
Replacing unreferenced package with stub: cxxbridge-macro
Replacing unreferenced package with stub: errno
Replacing unreferenced package with stub: errno-dragonfly
Replacing unreferenced package with stub: hermit-abi-0.1.19
Replacing unreferenced package with stub: hermit-abi
Replacing unreferenced package with stub: iana-time-zone-haiku
Replacing unreferenced package with stub: js-sys
Replacing unreferenced package with stub: link-cplusplus
Replacing unreferenced package with stub: scratch
Replacing unreferenced package with stub: smithay-client-toolkit
Replacing unreferenced package with stub: unicode-width
Replacing unreferenced package with stub: wasm-bindgen
Replacing unreferenced package with stub: wasm-bindgen-backend
Replacing unreferenced package with stub: wasm-bindgen-macro
Replacing unreferenced package with stub: wasm-bindgen-macro-support
Replacing unreferenced package with stub: wasm-bindgen-shared
Replacing unreferenced package with stub: winapi
Replacing unreferenced package with stub: winapi-i686-pc-windows-gnu
Replacing unreferenced package with stub: winapi-util
Replacing unreferenced package with stub: winapi-x86_64-pc-windows-gnu
Replacing unreferenced package with stub: windows-sys
Replacing unreferenced package with stub: windows_aarch64_gnullvm
Replacing unreferenced package with stub: windows_aarch64_msvc
Replacing unreferenced package with stub: windows_i686_gnu
Replacing unreferenced package with stub: windows_i686_msvc
Replacing unreferenced package with stub: windows_x86_64_gnu
Replacing unreferenced package with stub: windows_x86_64_gnullvm
Replacing unreferenced package with stub: windows_x86_64_msvc
Replacing unreferenced package with stub: android_system_properties
thread 'main' panicked at 'assertion failed: unreferenced.insert(name.to_string())', src/main.rs:712:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: abort      cargo vendor-filterer
```

My [`Cargo.toml is this one`](https://git.sr.ht/~whynothugo/shotman/tree/8c3a7edeeedd666fb51c2c87d6f77ad43330d9e1/item/Cargo.toml) plus:

```toml
[package.metadata.vendor-filter]
platforms = ["x86_64-unknown-linux-musl"]
```

**Comment by WhyNotHugo** [comment]
With current `main`, this yields:

```
Replacing unreferenced package with stub: windows_x86_64_gnullvm
Replacing unreferenced package with stub: windows_x86_64_msvc
Replacing unreferenced package with stub: android_system_properties
thread 'main' panicked at 'assertion failed: unreferenced.insert(name.to_string())', src/main.rs:707:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by WhyNotHugo** [comment]
I'm honestly having a really hard time trying to figure out this function (it's over 200LOC).

Looks like what's going on here is that a package is being replaced with a stub, and there's an assertion to confirm that the same package has not been visited before. In particular, `android_system_properties` seems to get visited twice, even though it's a single iteration of `read_dir`. I wonder how `ReadDir` behaves when the directory is mutated _during_ the iteration.

**Comment by WhyNotHugo** [comment]
Yeah, [this is undefined behaviour](https://pubs.opengroup.org/onlinepubs/9699919799/functions/readdir.html):

> If a file is removed from or added to the directory after the most recent call to [opendir()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/opendir.html) or [rewinddir()](https://pubs.opengroup.org/onlinepubs/9699919799/functions/rewinddir.html), whether a subsequent call to readdir() returns an entry for that file is unspecified.

**Comment by WhyNotHugo** [comment]
So I think what's happening here is that the underlying filesystem is mutated while iterating over the iterator returned by `readdir`, this seems to be undefined behaviour. In particular, it seems this results in the same file being returned more than twice.

I think the solution is to read all the entries into memory _and then_ process them. I'll try and come up with a patch.
